spring:
  application:
    name: academic-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:academic_platform}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:change_this_postgres_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: -1
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:change_this_rabbitmq_password}
    dynamic: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/academic-platform}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/academic-platform/protocol/openid-connect/certs}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

info:
  app:
    name: academic-service

academic:
  messaging:
    rabbitmq:
      exchange: ${ACADEMIC_EVENTS_EXCHANGE:academic.events.exchange}
      queue: ${ACADEMIC_EVENTS_QUEUE:academic.events.queue}
      routing-key: ${ACADEMIC_RESOURCE_COMPLETED_ROUTING_KEY:academic.resource.completed}

recommendation:
  service:
    url: ${RECOMMENDATION_SERVICE_URL:http://recommendation-service:8000}
