apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: academic-platform
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: academic-platform
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
