apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: academic-platform
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: academic-platform
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
