apiVersion: v1
kind: Secret
metadata:
  name: academic-platform-secrets
  namespace: academic-platform
  labels:
    app.kubernetes.io/name: academic-platform
    app.kubernetes.io/part-of: academic-platform
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: change_this_postgres_password
  RABBITMQ_USERNAME: academic_platform_rabbitmq
  RABBITMQ_PASSWORD: change_this_rabbitmq_password
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: change_this_keycloak_admin_password
  KC_DB_USERNAME: postgres
  KC_DB_PASSWORD: change_this_postgres_password
